name: Deploy

on:
  push:
    branches:
      - dev
      - master

jobs:
  deploy:
    name: Deploy
    permissions:
      contents: write
      id-token: write
      actions: read
    uses: O2OBOTS/o2obots-devops/.github/workflows/deploy.yml@master
    with:
      image_name: o2obotsteam/o2obots-app-frontend-prod
      environment: ${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }}
      k8s_context: ${{ github.ref == 'refs/heads/master' && vars.K8S_CONTEXT_PROD || vars.K8S_CONTEXT_DEV }}
      k8s_manifest: ${{ github.ref == 'refs/heads/master' && 'k8s/app.prod.yml' || 'k8s/app.dev.yml' }}
    secrets: inherit
